# Generated by Django 6.0.5 on 2026-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentprofile_class_10_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='preferred_level',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_stream',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='highest_qualification',
            field=models.CharField(choices=[('higher_secondary', 'Higher Secondary / 10+2'), ('polytechnic_diploma', 'Polytechnic Diploma'), ('graduate', 'Graduate'), ('post_graduate', 'Post-Graduate')], default='higher_secondary', max_length=25),
        ),
    ]
