# Generated by Django 6.0.5 on 2026-05-17 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('college_type', models.CharField(choices=[('govt', 'Government'), ('govt_aided', 'Government Aided'), ('self_financed', 'Self Financed'), ('private', 'Private')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('naac_grade', models.CharField(blank=True, max_length=10)),
                ('co_education', models.BooleanField(default=True)),
                ('hostel_available', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('phd', 'PhD')], max_length=15)),
                ('stream', models.CharField(choices=[('arts', 'Arts / Humanities'), ('commerce', 'Commerce'), ('science', 'Science'), ('engineering', 'Engineering'), ('medical', 'Medical'), ('law', 'Law'), ('management', 'Management'), ('education', 'Education'), ('computer', 'Computer Applications'), ('other', 'Other')], max_length=15)),
                ('duration_years', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=30, unique=True)),
                ('university_type', models.CharField(choices=[('state', 'State University'), ('central', 'Central University'), ('deemed', 'Deemed University'), ('private', 'Private University')], max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('admission_portal', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='university_logos/')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('naac_grade', models.CharField(blank=True, max_length=10)),
                ('nirf_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_courses', to='core.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='core.course')),
            ],
            options={
                'unique_together': {('college', 'course')},
            },
        ),
        migrations.CreateModel(
            name='AdmissionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g. 2026-2027', max_length=9)),
                ('application_start', models.DateField()),
                ('application_end', models.DateField()),
                ('application_link', models.URLField(blank=True)),
                ('application_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Applications Open'), ('closed', 'Applications Closed'), ('counselling', 'Counselling in Progress')], default='upcoming', max_length=15)),
                ('counselling_date', models.DateField(blank=True, null=True)),
                ('merit_list_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('college_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_cycles', to='core.collegecourse')),
            ],
            options={
                'ordering': ['-application_end'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_10th_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_12th_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('required_stream', models.CharField(blank=True, choices=[('arts', 'Arts / Humanities'), ('commerce', 'Commerce'), ('science', 'Science'), ('engineering', 'Engineering'), ('medical', 'Medical'), ('law', 'Law'), ('management', 'Management'), ('education', 'Education'), ('computer', 'Computer Applications'), ('other', 'Other')], help_text='Leave blank if any stream is accepted', max_length=15)),
                ('required_subjects', models.TextField(blank=True, help_text='Comma-separated list of required subjects in 12th')),
                ('board_type', models.CharField(choices=[('any', 'Any Board'), ('hbse', 'HBSE (Haryana Board)'), ('cbse', 'CBSE'), ('icse', 'ICSE')], default='any', max_length=10)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('entrance_exam', models.CharField(blank=True, max_length=100)),
                ('domicile_required', models.BooleanField(default=False)),
                ('category_reservation', models.JSONField(blank=True, default=dict, help_text='e.g. {"general": 50, "sc": 15, "bc_a": 16, "bc_b": 11}')),
                ('college_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_criteria', to='core.collegecourse')),
            ],
            options={
                'verbose_name_plural': 'eligibility criteria',
            },
        ),
        migrations.AddField(
            model_name='college',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='core.university'),
        ),
        migrations.CreateModel(
            name='CollegeCourseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('college_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='core.collegecourse')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requireddocument')),
            ],
            options={
                'unique_together': {('college_course', 'document')},
            },
        ),
    ]
