# Generated by Django 6.0.5 on 2026-05-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stream',
            field=models.CharField(choices=[('arts', 'Arts / Humanities'), ('commerce', 'Commerce'), ('science', 'Science'), ('engineering', 'Engineering'), ('medical', 'Medical'), ('law', 'Law'), ('management', 'Management'), ('education', 'Education'), ('computer', 'Computer Applications'), ('pharmacy', 'Pharmacy'), ('nursing', 'Nursing'), ('dental', 'Dental'), ('design', 'Design / Fine Arts'), ('agriculture', 'Agriculture / Dairy / Horticulture'), ('veterinary', 'Veterinary'), ('sports', 'Sports Science'), ('ayush', 'AYUSH'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='eligibilitycriteria',
            name='required_stream',
            field=models.CharField(blank=True, choices=[('arts', 'Arts / Humanities'), ('commerce', 'Commerce'), ('science', 'Science'), ('engineering', 'Engineering'), ('medical', 'Medical'), ('law', 'Law'), ('management', 'Management'), ('education', 'Education'), ('computer', 'Computer Applications'), ('pharmacy', 'Pharmacy'), ('nursing', 'Nursing'), ('dental', 'Dental'), ('design', 'Design / Fine Arts'), ('agriculture', 'Agriculture / Dairy / Horticulture'), ('veterinary', 'Veterinary'), ('sports', 'Sports Science'), ('ayush', 'AYUSH'), ('other', 'Other')], help_text='Leave blank if any stream is accepted', max_length=15),
        ),
    ]
