# Generated by Django 6.0.5 on 2026-05-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycriteria',
            name='min_graduation_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum graduation marks for PG eligibility', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='eligibilitycriteria',
            name='required_graduation',
            field=models.TextField(blank=True, help_text='Required bachelor/master degree for PG admission'),
        ),
    ]
