# Generated by Django 6.0.5 on 2026-05-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_pg_eligibility_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilitycriteria',
            name='entrance_exam',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
