# Generated by Django 6.0.5 on 2026-05-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_increase_entrance_exam_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('phd', 'PhD')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='stream',
            field=models.CharField(choices=[('arts', 'Arts / Humanities'), ('commerce', 'Commerce'), ('science', 'Science'), ('engineering', 'Engineering'), ('medical', 'Medical'), ('law', 'Law'), ('management', 'Management'), ('education', 'Education'), ('computer', 'Computer Applications'), ('pharmacy', 'Pharmacy'), ('nursing', 'Nursing'), ('dental', 'Dental'), ('design', 'Design / Fine Arts'), ('agriculture', 'Agriculture / Dairy / Horticulture'), ('veterinary', 'Veterinary'), ('sports', 'Sports Science'), ('ayush', 'AYUSH'), ('other', 'Other')], db_index=True, max_length=15),
        ),
    ]
