# Generated by Django 6.0.5 on 2026-05-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_course_level_stream_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioncycle',
            name='academic_year',
            field=models.CharField(db_index=True, help_text='e.g. 2026-2027', max_length=9),
        ),
        migrations.AlterField(
            model_name='admissioncycle',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Applications Open'), ('closed', 'Applications Closed'), ('counselling', 'Counselling in Progress')], db_index=True, default='upcoming', max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='universitycourse',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
